// EaglercraftX Client - Placeholder
// This file should be generated by compiling with: ./CompileJS.sh
// 
// The actual compiled JavaScript client is missing because:
// 1. The repository requires Minecraft 1.8 source code setup
// 2. You need to run: ./build_init && ./build_make_workspace
// 3. Then compile: ./CompileEPK.sh && ./CompileJS.sh
//
// For now, this placeholder shows an error message

function main() {
    const container = document.getElementById('game_frame');
    if (container) {
        container.innerHTML = `
            <div style="
                display: flex;
                align-items: center;
                justify-content: center;
                width: 100%;
                height: 100%;
                background-color: #1a1a1a;
                color: #00ff00;
                font-family: monospace;
                flex-direction: column;
                text-align: center;
                padding: 20px;
                box-sizing: border-box;
            ">
                <h1 style="margin-bottom: 20px;">⚠️ EaglercraftX Client Not Compiled</h1>
                <p style="font-size: 18px; max-width: 600px; line-height: 1.6;">
                    The JavaScript client (classes.js) is missing. This repository needs to be compiled locally first.
                </p>
                <p style="margin-top: 30px; color: #ffff00;">
                    <strong>To compile and deploy:</strong>
                </p>
                <pre style="
                    background-color: #0a0a0a;
                    border: 1px solid #00ff00;
                    padding: 15px;
                    border-radius: 5px;
                    margin-top: 20px;
                    text-align: left;
                    overflow-x: auto;
                ">
# 1. Run build setup (one-time)
./build_init
./build_make_workspace

# 2. Compile the project
./CompileEPK.sh
./CompileJS.sh

# 3. Push to GitHub
git add .
git commit -m "Add compiled client"
git push origin main
                </pre>
                <p style="margin-top: 30px; font-size: 14px; color: #888888;">
                    See <a href="GITHUB_PAGES_SETUP.md" style="color: #00ffff;">GITHUB_PAGES_SETUP.md</a> for detailed instructions
                </p>
            </div>
        `;
    }
}

// Auto-run main on page load
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', main);
} else {
    main();
}
